apps/contacts/urls.py
from django.urls import path, include

from . import views

app_name = "contacts"

urlpatterns = [
    path(
        "list/",
        include(
            [
                path("contacts/", views.ContactsListView.as_view(), name="list"),
            ]
        ),
    ),
    path("create/", views.ContactsCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.ContactsUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.ContactsDeleteView.as_view(), name="delete"),
]

apps/users_generation/urls.py
from django.urls import path, include

from apps.users_generation import views

app_name = "users_generation"
urlpatterns = [
    path(
        "users",
        include(
            [
                path("/<int:count>", views.UsersView.as_view(), name="with_args"),
            ]
        ),
    ),
]

core/urls.py
from django.urls import path, include


urlpatterns = [
    path("users_generation/", include("apps.users_generation.urls", namespace="users_generation")),
    path("", include("apps.users_generation.urls_root")),
    path("contacts/", include("apps.contacts.urls")),
]

apps/base/models.py
# Create your models here.

apps/contacts/models.py
from django.core.exceptions import ValidationError
from django.db import models


class Contacts(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.name} - {self.phone}"

    __repr__ = __str__

    def clean(self):
        if self.name.isdigit() or self.name is None:
            raise ValidationError("Enter right name!")
        if self.phone.isalpha() or self.phone is None:
            raise ValidationError("Enter right phone!")
        if not (self.phone.startswith("+380")):
            raise ValidationError("Phone must begin +380!")

apps/users_generation/models.py
# Create your models here.

apps/base/views.py
# Create your views here.

apps/contacts/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.contacts.models import Contacts


class ContactsListView(ListView):
    model = Contacts


class ContactsCreateView(CreateView):
    model = Contacts
    fields = (
        "name",
        "phone",
    )
    success_url = reverse_lazy("contacts:list")


class ContactsUpdateView(UpdateView):
    model = Contacts
    fields = (
        "id",
        "name",
        "phone",
    )
    success_url = reverse_lazy("contacts:list")


class ContactsDeleteView(DeleteView):
    model = Contacts
    success_url = reverse_lazy("contacts:list")

apps/users_generation/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render


def index(request: WSGIRequest):
    return render(
        request=request,
        template_name="index.html",
    )

apps/users_generation/views/index.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render


def index(request: WSGIRequest):
    return render(
        request=request,
        template_name="index.html",
    )

apps/users_generation/views/users_view.py
from django.views.generic import TemplateView

from apps.users_generation.services.generate_users import generate_users


class UsersView(TemplateView):
    template_name = "users_generation/users.html"

    def get_context_data(self, count: int, **kwargs) -> dict:

        context_data = super().get_context_data(**kwargs)

        context_data["title"] = "Users"
        context_data["count"] = count

        context_data["users"] = generate_users(count=count)

        return context_data

apps/templates/_helpers/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }} |
        {% endif %}
       USER GENERATION
    </title>
</head>
<body>
<div>
    {% include '_helpers/_menu.html' %}

    {% block content %}

    {% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_menu.html
<header>
    <ul>
        <li>
            <a href="{% url 'root:index' %}">Home</a>
        </li>
        <li>
            <a href="{% url 'users_generation:with_args' count=52 %}">Users</a>
        </li>
         <li>
            <a href="{% url 'contacts:list' %}">List of phones</a>
        </li>
    </ul>
</header>

apps/templates/contacts/contacts_confirm_delete.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}"?</p>

        <button type="submit">Confirm</button>
    </form>
{% endblock %}

apps/templates/contacts/contacts_form.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Submit</button>
    </form>
{% endblock %}

apps/templates/contacts/contacts_list.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <a href="{% url 'contacts:create' %}">
        <button>
            Create
        </button>
    </a>

    <ul>
        {% for contacts in object_list %}
            <li>
                <span>{{ contacts.name }}</span>
                <span> - </span>
                <span>{{ contacts.phone }}</span>
                <span> - </span>
                <span>{{ contacts.modified_at }}</span>

                <a href="{% url 'contacts:update' pk=contacts.id %}">
                    <button>
                        Edit
                    </button>
                </a>

                <a href="{% url 'contacts:delete' pk=contacts.id %}">
                    <button>
                        Delete
                    </button>
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

apps/templates/index.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <div>
        Main page
    </div>
{% endblock %}

apps/templates/users_generation/users.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <table>
    <tr><td>Name</td><td>Email</td><td>Password</td></tr>
        {% for user in users %}
            <tr>
                <td>
                    <span>{{ user.login }}</span>
                </td>
                <td>
                    <span>{{ user.email }}</span>
                </td>
                <td>
                    <span>{{ user.password }}</span>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}